---
title: "project_four"
author: "Leana Goetze"
date: "3/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

[Land Cover Data](http://geoportal.hawaii.gov/datasets/land-use-land-cover-lulc) made available by Hawaii Statewide GIS Program. Data measures the various land use types on the Hawaiian Islands. 
[Watershed Data](http://geoportal.hawaii.gov/datasets/watersheds) made available by Hawaii Statewide GIS Program. Data measures watershed characterisitics of the Hawaiian Islands. 

```{r}
# attach packages
library(tidyverse)
library(sf)
library(tmap)
library(here)
library(janitor)
library(mapview)
library(paletteer)
```

```{r}
# read in data
land <-read_sf(here("content","project","project_four","Land_Use_Land_Cover_LULC"), layer = "Land_Use_Land_Cover_LULC") %>% 
  clean_names()
```

```{r}
# select data of interest
land_two <- land %>% 
  select(landcover)
```

```{r}
# create an interactive map of land cover 
tmap_mode("view")+
  tm_shape(land_two)+
  tm_borders("white", lwd = .1)+
  tm_fill("landcover", legend.show = FALSE) +
  tm_basemap("Esri.WorldTerrain")+
  tm_layout(title = "Land use types of the Hawaiian Islands") 
```

```{r}
# read and filter watershed data (interested in area of Watershed in square miles)
water <-read_sf(here("content","project","project_four","Watersheds"), layer = "Watersheds") %>% 
  clean_names() %>% 
  select(-objectid) %>% 
  rename("Area (square miles)" = area_sqmi)
```

```{r}
# create an interactive map of the watershed data
tmap_mode("view")+
  tm_shape(water)+
  tm_borders("white", lwd = .1)+
  tm_fill("Area (square miles)", palette = "Reds") +
  tm_layout(title = "Size of Hawaiian Watersheds (Square Miles)")+
  tm_basemap("Esri.WorldTerrain")
```
